import React from 'react';

// every dealer will have a table with 9 seats, 
// a deck of cards, 
// and be attached to the bank

export function Deck(){
    const deck = [
        {Suite: "Heart", Number: 1}, 
        {Suite: "Heart", Number: 2}, 
        {Suite: "Heart", Number: 3},
        {Suite: "Heart", Number: 4},
        {Suite: "Heart", Number: 5},
        {Suite: "Heart", Number: 6},
        {Suite: "Heart", Number: 7},
        {Suite: "Heart", Number: 8},
        {Suite: "Heart", Number: 9},
        {Suite: "Heart", Number: 10},
        {Suite: "Heart", Number: 11},
        {Suite: "Heart", Number: 12},
        {Suite: "Heart", Number: 13},
        {Suite: "Spade", Number: 1}, 
        {Suite: "Spade", Number: 2}, 
        {Suite: "Spade", Number: 3},
        {Suite: "Spade", Number: 4},
        {Suite: "Spade", Number: 5},
        {Suite: "Spade", Number: 6},
        {Suite: "Spade", Number: 7},
        {Suite: "Spade", Number: 8},
        {Suite: "Spade", Number: 9},
        {Suite: "Spade", Number: 10},
        {Suite: "Spade", Number: 11},
        {Suite: "Spade", Number: 12},
        {Suite: "Spade", Number: 13},
        {Suite: "Club", Number: 1}, 
        {Suite: "Club", Number: 2}, 
        {Suite: "Club", Number: 3},
        {Suite: "Club", Number: 4},
        {Suite: "Club", Number: 5},
        {Suite: "Club", Number: 6},
        {Suite: "Club", Number: 7},
        {Suite: "Club", Number: 8},
        {Suite: "Club", Number: 9},
        {Suite: "Club", Number: 10},
        {Suite: "Club", Number: 11},
        {Suite: "Club", Number: 12},
        {Suite: "Club", Number: 13},
        {Suite: "Diamond", Number: 1}, 
        {Suite: "Diamond", Number: 2}, 
        {Suite: "Diamond", Number: 3},
        {Suite: "Diamond", Number: 4},
        {Suite: "Diamond", Number: 5},
        {Suite: "Diamond", Number: 6},
        {Suite: "Diamond", Number: 7},
        {Suite: "Diamond", Number: 8},
        {Suite: "Diamond", Number: 9},
        {Suite: "Diamond", Number: 10},
        {Suite: "Diamond", Number: 11},
        {Suite: "Diamond", Number: 12},
        {Suite: "Diamond", Number: 13},
    ]
}



